# Generated by Django 2.2.7 on 2019-11-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Manufacturer')),
            ],
        ),
    ]
