# Generated by Django 2.2.7 on 2019-11-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191130_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='console',
            old_name='maker',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='maker',
            new_name='manufacturer',
        ),
    ]
