# Generated by Django 3.0 on 2019-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191130_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='console',
        ),
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.ManyToManyField(to='shop.Console'),
        ),
    ]
