# Generated by Django 3.0 on 2019-12-08 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191207_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Min is 0.00, and max is 999.99', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Min is 0.00, and max is 999.99', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
