# Generated by Django 2.2.7 on 2019-12-05 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20191205_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 13, 51, 5, 214489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
