# Generated by Django 2.2.7 on 2019-12-05 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20191205_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 5, 14, 11, 23, 100069, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='unknown', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, default='normal', max_length=100, null=True),
        ),
    ]
