# Generated by Django 3.0 on 2019-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20191205_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
    ]
